use crate::model::kotoba::Kotoba;
use crate::model::mono::Mono;

pub fn sendagi() -> Vec<Mono> {
    return vec![
        Mono {
            namae: "お食事・ドリンクメニュー",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("メニュー"),
                Kotoba::from_str("お食事・ドリンクメニュー"),
            ],
            fuda: vec!["サービス"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_bcd4948bcde34ad595f70b8af7cbc19d~mv2.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "設備・レンタルメニュー",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("メニュー"),
                Kotoba::from_str("設備・レンタルメニュー"),
            ],
            fuda: vec!["設備", "サービス"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_7c9fa02ef6634f81979d603bf69e68f5~mv2.jpg",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "お知らせ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("メニュー"),
                Kotoba::from_str("お知らせ"),
            ],
            fuda: vec!["キャンペーン"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_8c93f61f8719446d9e246ae2e02fd966~mv2.jpg",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "30分",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_vec(vec!["プラン", "料金プラン"]),
                Kotoba::from_str("30分"),
            ],
            fuda: vec!["税込み"],
            neuchi: 300,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_8c9059dc85674638a7189a0da7405c30~mv2.png",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "3Hプラン",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_vec(vec!["プラン", "料金プラン"]),
                Kotoba::from_vec(vec!["3時間", "3H"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 1500,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_8c9059dc85674638a7189a0da7405c30~mv2.png",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "5Hプラン",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_vec(vec!["プラン", "料金プラン"]),
                Kotoba::from_vec(vec!["5時間", "5H"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 2000,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_8c9059dc85674638a7189a0da7405c30~mv2.png",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "1dayプラン",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_vec(vec!["プラン", "料金プラン"]),
                Kotoba::from_vec(vec!["1day", "1日"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 2000,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_8c9059dc85674638a7189a0da7405c30~mv2.png",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "月額プラン",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_vec(vec!["プラン", "料金プラン"]),
                Kotoba::from_vec(vec!["月額プラン"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 15000,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_8c9059dc85674638a7189a0da7405c30~mv2.png",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "月額会員",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_vec(vec!["プラン", "料金プラン"]),
                Kotoba::from_vec(vec!["月額会員"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_8c9059dc85674638a7189a0da7405c30~mv2.png",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "ホットサンド(ハムたまご)サラダ付",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_str("ホットサンド"),
                Kotoba::from_vec(vec!["ハムたまご", "ハム卵"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 500,
            comment: "ハムとタマゴフィリング\nほっとするほどの安心感\nパンのサクッとベストマッチ",
            allergen: Some(vec!["卵", "乳"]),
            moto: Some(vec![
                "パン",
                "ハム",
                "卵",
                "チーズ",
                "マヨネーズ",
                "ミニトマト",
                "プチトマト",
                "トマト",
                "ベビーリーフ",
                "胡麻ドレッシング",
            ]),
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_61fea419aeb34bb5bf7b3741d1f6a2f9~mv2.jpg",
            url: "https://www.comfull.co.jp/",
        },
        Mono {
            namae: "ホットサンド(ハムチーズ) サラダ付",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_str("ホットサンド"),
                Kotoba::from_vec(vec!["ハムチーズ"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 500,
            comment: "ハムとチーズとマヨ\n定番だが最高の組み合わせ\n間違いない美味しさ",
            allergen: Some(vec!["卵", "乳"]),
            moto: Some(vec![
                "パン",
                "ハム",
                "チーズ",
                "マヨネーズ",
                "ミニトマト",
                "プチトマト",
                "トマト",
                "ベビーリーフ",
                "胡麻ドレッシング",
            ]),
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_0a0079c440124ceda322018ca8f9c3dd~mv2.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "ホットサンド(ツナチーズ) サラダ付",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_str("ホットサンド"),
                Kotoba::from_vec(vec!["ツナチーズ"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 500,
            comment: "ツナマヨとチーズ\n美味しい　×　美味しい\n＝　すごく美味しい",
            allergen: Some(vec!["乳"]),
            moto: Some(vec![
                "パン",
                "ツナ",
                "チーズ",
                "ミニトマト",
                "プチトマト",
                "トマト",
                "ベビーリーフ",
                "胡麻ドレッシング",
            ]),
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_81e696de82c24991a12005331aec1c23~mv2.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "アサヒスーパードライ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_vec(vec!["アサヒスーパードライ", "スーパードライ"]),
            ],
            fuda: vec!["税込み", "アサヒ"],
            neuchi: 500,
            comment: "ビールといえばこちら\nのど越しすっきり辛口",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_a6f013a04bf14896961c440ff7cec0d4~mv2.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "サッポロ黒ラベル",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_vec(vec!["サッポロ黒ラベル", "黒ラベル"]),
            ],
            fuda: vec!["税込み", "サッポロ"],
            neuchi: 500,
            comment: "大人の生でおなじみ\nさわやかクリーミー泡",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_5038eea84c4e49338c71941368048cda~mv2.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "ハイネケン",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_vec(vec!["ハイネケン"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 600,
            comment: "海外ビールの代名詞\nベリー飲みやすいビール",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_99e9ba5726b44ef996213ade57239b10~mv2.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "コロナビール",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_vec(vec!["コロナビール"]),
            ],
            fuda: vec!["税込み"],
            neuchi: 600,
            comment: "メキシコ発リゾートビール\nおしゃれにラッパ飲み",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://static.wixstatic.com/media/e38835_e18b3efa59c240d190c849cd45a55b64~mv2.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "水",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_vec(vec!["水"]),
            ],
            fuda: vec!["フリードリンク"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image:
                "https://www.suntory.co.jp/water/tennensui/assets/img/product/still_water_1_img.png",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "烏龍茶",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_vec(vec!["ウーロン茶", "烏龍茶", "お茶"]),
            ],
            fuda: vec!["フリードリンク"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image: "https://www.suntory.co.jp/softdrink/oolongtea/img/product/oolongtea_bottle.png",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "ホットコーヒー",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("コーヒー"),
                Kotoba::from_vec(vec!["ブレンドコーヒー", "ホットコーヒー"]),
            ],
            fuda: vec!["フリードリンク"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/1024px-A_small_cup_of_coffee.JPG",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "カフェオレ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("コーヒー"),
                Kotoba::from_vec(vec!["カフェオレ"]),
            ],
            fuda: vec!["フリードリンク"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image: "https://farm4.static.flickr.com/3606/3597255463_e6b7a81b66_z.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "カフェモカ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("コーヒー"),
                Kotoba::from_vec(vec!["カフェモカ"]),
            ],
            fuda: vec!["フリードリンク"],
            neuchi: 0,
            comment: "",
            allergen: None,
            moto: None,
            calorie: None,
            image: "https://farm8.static.flickr.com/7432/11830009375_e60256ecbd_z.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
        Mono {
            namae: "充電ケーブル",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("レンタル"),
                Kotoba::from_vec(vec!["充電ケーブル", "充電コード", "充電器"]),
            ],
            fuda: vec!["iphone対応", "android対応"],
            neuchi: 0,
            comment: "iphone, android対応、Micro USB / Type C / ライトニング対応",
            allergen: None,
            moto: None,
            calorie: None,
            image: "https://m.media-amazon.com/images/I/61PhXHjBzxL._AC_UL320_.jpg",
            url: "https://www.comfull.co.jp/menu",
        },
    ];
}
