service: omoinas
provider:
  name: aws
  runtime: rust
  memorySize: 128
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*" 
  stage: ${opt:stage, self:custom.defaultStage}
package:
  individually: true
custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./conf/dev.yml)}
      prd: ${file(./conf/prd.yml)}
  rust:
    dockerTag: '0.2.6-rust-1.42.0'

plugins:
  - serverless-rust

functions:
  ukekotae:
    handler: omoinas.ukekotae
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}
      COTOHA_CLIENT_ID: ${self:custom.otherfile.environment.${self:provider.stage}.COTOHA_CLIENT_ID}
      COTOHA_CLIENT_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.COTOHA_CLIENT_SECRET}
    events:
      - http:
          path: /ukekotae
          method: POST

  tanamono:
    handler: omoinas.tanamono
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}

  resetOmise:
    handler: omoinas.reset_omise
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}

  setOmise:
    handler: omoinas.set_omise
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}

  getOmise:
    handler: omoinas.api
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}
    events:
      - http:
          path: /omise/{clientId}/{omiseId}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                clientId: true,
                omiseId: true,

  createDenpyo:
    handler: omoinas.create_denpyo
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}

  resetDenpyo:
    handler: omoinas.reset_denpyo
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}

  getDenpyo:
    handler: omoinas.api
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}
    events:
      - http:
          path: /omise/{clientId}/{omiseId}/maroudo/{maroudoId}/denpyo
          method: GET
          cors: true
          request:
            parameters:
              paths:
                clientId: true,
                omiseId: true,
                maroudoId: true,

