use crate::model::mono::Mono;
use crate::model::Kotoba;

pub fn shinkansen() -> Vec<Mono> {
    return vec![
        Mono {
            namae: "車内販売メニュー",
            category: vec![Kotoba::from_str("モノ"), Kotoba::from_str("メニュー")],
            fuda: vec![],
            neuchi: 0,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/topics/get_image?id=215&image_number=1",
            url: "https://www.jr-cp.co.jp/pdf/service/wagon_menu_list.pdf",
        },
        Mono {
            namae: "スジャータアイスクリーム(バニラ)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["アイス", "アイスクリーム"]),
                Kotoba::from_vec(vec!["バニラアイス", "バニラアイスクリーム"]),
            ],
            fuda: vec!["冷たい", "甘い", "バニラ", "スジャータ"],
            neuchi: 290,
            comment: "",
            allergen: Some(vec!["乳", "卵"]),
            ingredients: Some(vec!["牛乳", "卵", "砂糖", "バニラエッセンス"]),
            calorie: Some(232),
            image: "https://www.jr-cp.co.jp/services/38/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=1#wagon_content",
        },
        Mono {
            namae: "スジャータアイスクリーム(いちご)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["アイス", "アイスクリーム"]),
                Kotoba::from_vec(vec!["ストロベリーアイス", "ストロベリーアイスクリーム"]),
            ],
            fuda: vec![
                "冷たい",
                "甘い",
                "苺",
                "ストロベリー",
                "スジャータ",
                "期間限定",
            ],
            neuchi: 330,
            comment: "",
            allergen: Some(vec!["乳"]),
            ingredients: Some(vec!["牛乳", "砂糖", "苺", "ストロベリー"]),
            calorie: Some(162),
            image: "https://www.jr-cp.co.jp/services/281/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=1#wagon_content",
        },
        Mono {
            namae: "スジャータアイスクリーム(ピスタチオ)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["アイス", "アイスクリーム"]),
                Kotoba::from_str("ピスタチオアイス"),
            ],
            fuda: vec![
                "冷たい",
                "甘い",
                "ピスタチオ",
                "スジャータ",
                "新しい",
                "期間限定",
            ],
            neuchi: 390,
            comment: "",
            allergen: Some(vec!["乳"]),
            ingredients: Some(vec!["牛乳", "砂糖", "ピスタチオ"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/276/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=1#wagon_content",
        },
        Mono {
            namae: "ウェッジ月刊誌",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("読み物"),
                Kotoba::from_str("雑誌"),
                Kotoba::from_vec(vec!["ウェッジ", "wedge"]),
            ],
            fuda: vec![],
            neuchi: 550,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/50/get_image?image_number=1<Paste>",
            url: "https://www.jr-cp.co.jp/services/wagon?space=1#wagon_content",
        },
        Mono {
            namae: "ひととき",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("読み物"),
                Kotoba::from_str("雑誌"),
                Kotoba::from_str("ひととき"),
            ],
            fuda: vec![],
            neuchi: 550,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/51/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=1#wagon_content",
        },
        Mono {
            namae: "オーボンヴュータン／プティフールセック",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["新幹線スイーツ", "スイーツ"]),
                Kotoba::from_str("プティフールセック"),
            ],
            fuda: vec!["甘い", "焼き菓子", "オーボンヴュータン"],
            neuchi: 590,
            comment: "",
            allergen: Some(vec!["小麦", "卵", "大豆"]),
            ingredients: Some(vec!["小麦粉", "卵", "砂糖", "バター", "大豆"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/41/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "メゾンカイザー　フランボワーズショコラフィナンシェ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["新幹線スイーツ", "スイーツ"]),
                Kotoba::from_str("ショコラフィナンシェ"),
            ],
            fuda: vec!["甘い", "焼き菓子", "メゾンカイザー"],
            neuchi: 540,
            comment: "",
            allergen: Some(vec!["小麦", "卵", "大豆"]),
            ingredients: Some(vec!["小麦粉", "卵", "砂糖", "バター", "大豆", "カカオマス"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/255/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "メゾンカイザー　大人のキャラメルクッキー",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["新幹線スイーツ", "スイーツ"]),
                Kotoba::from_str("キャラメルクッキー"),
            ],
            fuda: vec!["甘い", "焼き菓子", "メゾンカイザー"],
            neuchi: 430,
            comment: "",
            allergen: Some(vec!["小麦", "卵", "大豆"]),
            ingredients: Some(vec!["小麦粉", "卵", "砂糖", "バター", "大豆"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/254/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "ストーンサークル･クォーター(赤)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("赤ワイン"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 500,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/73/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "ストーンサークル･クォーター(白)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("白ワイン"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 500,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/74/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "山崎12年(50ml)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ウイスキー"),
                Kotoba::from_str("山崎"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 1180,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/192/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "ジャックダニエルブラック(50ml)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ウイスキー"),
                Kotoba::from_str("ジャックダニエル"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 870,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/191/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "大吟醸カップ(210ml)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("日本酒"),
                Kotoba::from_str("大吟醸カップ"),
            ],
            fuda: vec!["冷たい", "ワンカップ"],
            neuchi: 370,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/219/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "ウィルキンソンタンサン缶(250ml)",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_vec(vec!["炭酸水", "炭酸飲料", "炭酸"]),
                Kotoba::from_str("ウィルキンソン"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 100,
            comment: "",
            allergen: Some(vec![]),
            ingredients: Some(vec!["炭酸"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/189/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "マカデミアナッツ＆さくさくチーズ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["おつまみ", "お摘まみ"]),
                Kotoba::from_vec(vec!["マカデミアナッツ", "マカダミアナッツ"]),
            ],
            fuda: vec![],
            neuchi: 340,
            comment: "",
            allergen: Some(vec!["小麦", "乳", "ナッツ"]),
            ingredients: Some(vec!["小麦粉", "チーズ", "マカダミアナッツ"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/71/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "柿の種とピーナッツ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["おつまみ", "お摘まみ"]),
                Kotoba::from_vec(vec!["柿の種", "柿ピー"]),
            ],
            fuda: vec!["ピーナッツ"],
            neuchi: 250,
            comment: "",
            allergen: Some(vec!["大豆", "ピーナッツ"]),
            ingredients: Some(vec!["米粉", "食塩", "ピーナッツ"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/25/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "プレミアムミックスナッツ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["おつまみ", "お摘まみ"]),
                Kotoba::from_str("ミックスナッツ"),
            ],
            fuda: vec![],
            neuchi: 310,
            comment: "",
            allergen: Some(vec!["大豆", "アーモンド", "ピーナッツ"]),
            ingredients: Some(vec!["食塩", "アーモンド", "ピーナッツ"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/27/get_image?image_number=1<Paste>",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "鯛入りちくわ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["おつまみ", "お摘まみ"]),
                Kotoba::from_vec(vec!["ちくわ", "竹輪"]),
            ],
            fuda: vec![],
            neuchi: 370,
            comment: "",
            allergen: Some(vec!["蟹", "海老"]),
            ingredients: Some(vec!["介党鱈", "食塩", "鯛"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/29/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "やわらかビーフジャーキースパイシー味",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["おつまみ", "お摘まみ"]),
                Kotoba::from_str("ビーフジャーキー"),
            ],
            fuda: vec![],
            neuchi: 310,
            comment: "",
            allergen: Some(vec!["牛肉"]),
            ingredients: Some(vec!["牛肉", "食塩"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/124/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "しっとりやわらかいか燻製",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["おつまみ", "お摘まみ"]),
                Kotoba::from_vec(vec!["いか燻製", "以下燻製", "イカ", "燻製", "鯣", "鯣イカ"]),
            ],
            fuda: vec![],
            neuchi: 370,
            comment: "",
            allergen: Some(vec![]),
            ingredients: Some(vec!["するめいか", "食塩"]),
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/213/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "ロッテトッポ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お菓子", "菓子"]),
                Kotoba::from_str("トッポ"),
            ],
            fuda: vec!["ロッテ"],
            neuchi: 260,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/209/get_image?image_number=1<Paste>",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "チップスター極 海の精焼き塩使用しお味",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お菓子", "菓子"]),
                Kotoba::from_str("チップスターしお味"),
            ],
            fuda: vec![
                "ヤマザキ",
                "しお味",
                "チップスター",
                "ポテトチップス",
                "ポテチ",
            ],
            neuchi: 200,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/34/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "チップスター松阪牛ステーキ味",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お菓子", "菓子"]),
                Kotoba::from_str("チップスターステーキ味"),
            ],
            fuda: vec![
                "ヤマザキ",
                "ステーキ味",
                "チップスター",
                "ポテトチップス",
                "ポテチ",
            ],
            neuchi: 200,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/214/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "ゆかり濃厚おつまみスナック",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お菓子", "菓子"]),
                Kotoba::from_vec(vec!["おつまみスナック", "お摘まみスナック"]),
            ],
            fuda: vec!["スナック"],
            neuchi: 200,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/151/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "柿もなか2個入",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お菓子", "菓子"]),
                Kotoba::from_vec(vec!["柿もなか", "柿最中", "最中"]),
            ],
            fuda: vec![],
            neuchi: 300,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/212/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "うなぎパイ12本入",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_str("お土産"),
                Kotoba::from_vec(vec!["うなぎパイ", "鰻パイ"]),
            ],
            fuda: vec!["春華堂", "おすすめ"],
            neuchi: 970,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/137/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "崎陽軒　真空パックシウマイ30個入",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_str("お土産"),
                Kotoba::from_vec(vec!["シウマイ", "シュウマイ"]),
            ],
            fuda: vec!["崎陽軒"],
            neuchi: 970,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/46/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=2#wagon_content",
        },
        Mono {
            namae: "特撰肉づくし",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お弁当", "弁当", "駅弁"]),
                Kotoba::from_str("特撰肉づくし"),
            ],
            fuda: vec![],
            neuchi: 1350,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/264/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "春満喫 鯛めしとたけのこ御膳",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お弁当", "弁当", "駅弁"]),
                Kotoba::from_vec(vec!["たけのこ御膳", "筍御膳"]),
            ],
            fuda: vec![],
            neuchi: 1150,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/279/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "焼売炒飯弁當",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お弁当", "弁当", "駅弁"]),
                Kotoba::from_vec(vec!["シュウマイ炒飯弁当", "炒飯", "チャーハン"]),
            ],
            fuda: vec!["シュウマイ", "シウマイ"],
            neuchi: 940,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/259/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "特製幕之内御膳",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お弁当", "弁当", "駅弁"]),
                Kotoba::from_vec(vec!["特製幕之内御膳", "幕の内御膳", "幕の内", "幕内"]),
            ],
            fuda: vec![],
            neuchi: 1380,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/57/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "東海道新幹線弁当",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お弁当", "弁当", "駅弁"]),
                Kotoba::from_str("東海道新幹線弁当"),
            ],
            fuda: vec![],
            neuchi: 1000,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/142/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "厚切りヒレカツサンド",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["サンドイッチ", "サンドウィッチ"]),
                Kotoba::from_str("ヒレカツサンド"),
            ],
            fuda: vec!["ヒレカツ", "カツサンド"],
            neuchi: 750,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/251/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "朝のおむすび弁当",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お弁当", "弁当", "駅弁"]),
                Kotoba::from_vec(vec!["おむすび弁当", "おむすび", "おにぎり"]),
            ],
            fuda: vec![],
            neuchi: 450,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/143/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "牛カルビ焼肉重",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["お弁当", "弁当", "駅弁"]),
                Kotoba::from_vec(vec!["牛カルビ焼肉弁当", "カルビ", "焼肉", "焼き肉"]),
            ],
            fuda: vec![],
            neuchi: 920,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/263/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "プレミアムミックスサンド",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["サンドイッチ", "サンドウィッチ"]),
                Kotoba::from_str("ミックスサンド"),
            ],
            fuda: vec![],
            neuchi: 700,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/127/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "カツ＆ポテトサンド",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["サンドイッチ", "サンドウィッチ"]),
                Kotoba::from_str("カツポテトサンド"),
            ],
            fuda: vec!["カツサンド", "カツポテト"],
            neuchi: 420,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/256/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "ハムチーズ＆たまごサンド",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["サンドイッチ", "サンドウィッチ"]),
                Kotoba::from_str("ハムチーズたまごサンド"),
            ],
            fuda: vec!["ハム", "チーズ", "たまご", "卵", "玉子", "サンド"],
            neuchi: 420,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/129/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "柔らかカツサンド",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["サンドイッチ", "サンドウィッチ"]),
                Kotoba::from_str("カツサンド"),
            ],
            fuda: vec![],
            neuchi: 650,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/267/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "ハムサラダ＆ハムチーズサンド",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("食べ物"),
                Kotoba::from_vec(vec!["サンドイッチ", "サンドウィッチ"]),
                Kotoba::from_str("ハムサラダサンド"),
            ],
            fuda: vec!["ハム", "サラダ", "サンド"],
            neuchi: 470,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/261/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=3#wagon_content",
        },
        Mono {
            namae: "アイスコーヒー",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("コーヒー"),
                Kotoba::from_vec(vec!["アイスコーヒー", "冷コー"]),
            ],
            fuda: vec!["冷たい"],
            neuchi: 330,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/174/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=4#wagon_content",
        },
        Mono {
            namae: "ホットコーヒー",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("コーヒー"),
                Kotoba::from_str("ホットコーヒー"),
            ],
            fuda: vec!["あたたかい", "暖かい"],
            neuchi: 320,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/157/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=4#wagon_content",
        },
        Mono {
            namae: "サントリー ザ･プレミアムモルツ 350ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_str("サントリープレミアムモルツ"),
            ],
            fuda: vec!["冷たい", "サントリー", "モルツ", "プレモル"],
            neuchi: 340,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/1/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "サントリー　ザ・プレミアムモルツ香るエール　350㎖",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_str("サントリープレミアムモルツエール"),
            ],
            fuda: vec!["冷たい", "サントリー", "モルツ", "エール"],
            neuchi: 340,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/272/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "キリン一番搾り 350ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_vec(vec!["キリン一番搾り", "一番搾り"]),
            ],
            fuda: vec!["冷たい", "キリン"],
            neuchi: 310,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/2/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "サッポロエビス 350ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_vec(vec!["サッポロエビス", "エビス", "ヱビス"]),
            ],
            fuda: vec!["冷たい", "サッポロ"],
            neuchi: 330,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/5/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "アサヒスーパードライ 350ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ビール"),
                Kotoba::from_vec(vec!["アサヒスーパードライ", "スーパードライ", "極度乾燥"]),
            ],
            fuda: vec!["冷たい", "アサヒ"],
            neuchi: 310,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/3/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "サントリー角ハイボール 350ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("ハイボール"),
                Kotoba::from_vec(vec!["サントリー角ハイボール", "ハイボール"]),
            ],
            fuda: vec!["冷たい", "サントリー"],
            neuchi: 270,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/8/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "タカラ缶チューハイレモン 350ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("チューハイ"),
                Kotoba::from_vec(vec!["タカラ缶チューハイレモン", "缶チューハイ"]),
            ],
            fuda: vec!["冷たい", "タカラ"],
            neuchi: 270,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/9/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "こだわり酒場のレモンサワー　500㎖",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_vec(vec!["お酒", "酒", "アルコール"]),
                Kotoba::from_str("サワー"),
                Kotoba::from_str("レモンサワー"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 270,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/280/get_image?image_number=1<Paste>",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "旅茶房静岡茶500ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_vec(vec!["お茶", "茶", "緑茶"]),
                Kotoba::from_str("旅茶房静岡茶"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 160,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/253/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "ナチュラルミネラルウォーター Mont Fuji / 500ｍｌ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_vec(vec!["ミネラルウェーター", "水", "お水"]),
            ],
            fuda: vec!["冷たい"],
            neuchi: 130,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/20/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "オレンジジュース100 / 280ｍｌ",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_str("ジュース"),
                Kotoba::from_str("オレンジジュース"),
            ],
            fuda: vec!["冷たい"],
            neuchi: 180,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/17/get_image?image_number=1<Paste>",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "ポカリスエット/ 300ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_str("ジュース"),
                Kotoba::from_vec(vec!["ポカリスエット", "ポカリスウェット", "ポカリ"]),
            ],
            fuda: vec!["冷たい"],
            neuchi: 130,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/16/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "Welch'sグレープ50 280PET",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_str("ジュース"),
                Kotoba::from_str("ウェルチグレープ"),
            ],
            fuda: vec!["冷たい", "ウェルチ"],
            neuchi: 140,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/241/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
        Mono {
            namae: "コカ･コーラ ボトル /280ml",
            category: vec![
                Kotoba::from_str("モノ"),
                Kotoba::from_str("飲み物"),
                Kotoba::from_str("ソフトドリンク"),
                Kotoba::from_str("ジュース"),
                Kotoba::from_vec(vec!["コカコーラ", "コーラ"]),
            ],
            fuda: vec!["冷たい", "炭酸", "炭酸飲料"],
            neuchi: 130,
            comment: "",
            allergen: None,
            ingredients: None,
            calorie: None,
            image: "https://www.jr-cp.co.jp/services/15/get_image?image_number=1",
            url: "https://www.jr-cp.co.jp/services/wagon?space=5#wagon_content",
        },
    ];
}
