service: motenas
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - '*'

custom:
  defaultStage: dev
  otherfile:
    dev: ${file(./conf/line-dev.yml)}
    prd: ${file(./conf/line-prd.yml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  lineCheckOmise:
    handler: bin/line_api
    runtime: go1.x
    environment: ${self:custom.otherfile.${self:provider.stage}}
    events:
      - http:
          path: line-api/omise/check
          method: post
          cors: true
          origin: '*'

  lineSetOmise:
    handler: bin/line_api
    runtime: go1.x
    environment: ${self:custom.otherfile.${self:provider.stage}}
    events:
      - http:
          path: line-api/omise/set
          method: post
          cors: true
          origin: '*'

  lineEnterOmise:
    handler: bin/line_api
    runtime: go1.x
    environment: ${self:custom.otherfile.${self:provider.stage}}
    events:
      - http:
          path: line-api/omise/enter
          method: post
          cors: true
          origin: '*'

  lineTokishirazuLlcPassengers:
    handler: bin/line
    runtime: go1.x
    environment: ${self:custom.otherfile.${self:provider.stage}}
    events:
      - http:
          path: line-tokishirazu-llc-passengers
          method: post
          cors: true
  
  lineComfullCoJpSendagi:
    handler: bin/line
    runtime: go1.x
    environment: ${self:custom.otherfile.${self:provider.stage}}
    events:
      - http:
          path: line-comfull-co-jp-sendagi
          method: post
          cors: true
  
