service: motenas
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: dev
  otherfile:
    lineBachan:
      dev: ${file(./conf/line-bachan-dev.yml)}
    lineMinarai:
      dev: ${file(./conf/line-minarai-dev.yml)}
  rust:
    dockerTag: 'some-custom-tag'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  lineBachan:
    handler: bin/line-bachan
    runtime: go1.x
    environment:
      CHARA_NAME:  ${self:custom.otherfile.lineBachan.${self:provider.stage}.CHARA_NAME}
      CHANNEL_SECRET: ${self:custom.otherfile.lineBachan.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.lineBachan.${self:provider.stage}.CHANNEL_TOKEN}
      ADMIN_CHANNEL_SECRET: ${self:custom.otherfile.lineBachan.${self:provider.stage}.ADMIN_CHANNEL_SECRET}
      ADMIN_CHANNEL_TOKEN: ${self:custom.otherfile.lineBachan.${self:provider.stage}.ADMIN_CHANNEL_TOKEN}

    events:
      - http:
          path: line-bachan
          method: post
          cors: true
  
  lineBachanAdmin:
    handler: bin/line-bachan-admin
    runtime: go1.x
    environment:
      CHANNEL_SECRET: ${self:custom.otherfile.lineBachan.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.lineBachan.${self:provider.stage}.CHANNEL_TOKEN}
      ADMIN_CHANNEL_SECRET: ${self:custom.otherfile.lineBachan.${self:provider.stage}.ADMIN_CHANNEL_SECRET}
      ADMIN_CHANNEL_TOKEN: ${self:custom.otherfile.lineBachan.${self:provider.stage}.ADMIN_CHANNEL_TOKEN}

    events:
      - http:
          path: line-bachan-admin
          method: post
          cors: true
  
  
  lineMinarai:
    handler: bin/line-minarai
    runtime: go1.x
    environment:
      CHARA_NAME:  ${self:custom.otherfile.lineMinarai.${self:provider.stage}.CHARA_NAME}
      CHANNEL_SECRET: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.CHANNEL_TOKEN}
      ADMIN_CHANNEL_SECRET: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.ADMIN_CHANNEL_SECRET}
      ADMIN_CHANNEL_TOKEN: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.ADMIN_CHANNEL_TOKEN}

    events:
      - http:
          path: line-minarai
          method: post
          cors: true
  
  lineMinaraiAdmin:
    handler: bin/line-minarai-admin
    runtime: go1.x
    environment:
      CHANNEL_SECRET: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.CHANNEL_TOKEN}
      ADMIN_CHANNEL_SECRET: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.ADMIN_CHANNEL_SECRET}
      ADMIN_CHANNEL_TOKEN: ${self:custom.otherfile.lineMinarai.${self:provider.stage}.ADMIN_CHANNEL_TOKEN}

    events:
      - http:
          path: line-minarai-admin
          method: post
          cors: true
  
  
