service: motenas
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: dev
  otherfile:
    lineTokishirazuLlcBachan:
      dev: ${file(./conf/line-tokishirazu-llc-bachan-dev.yml)}
    lineTokishirazuLlcMinarai:
      dev: ${file(./conf/line-tokishirazu-llc-minarai-dev.yml)}
  rust:
    dockerTag: 'some-custom-tag'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  lineBachan:
    handler: bin/line
    runtime: go1.x
    environment:
      CHARA_NAME:  ${self:custom.otherfile.lineTokishirazuLlcBachan.${self:provider.stage}.CHARA_NAME}
      CHANNEL_SECRET: ${self:custom.otherfile.lineTokishirazuLlcBachan.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.lineTokishirazuLlcBachan.${self:provider.stage}.CHANNEL_TOKEN}
      ADMIN_GROUP_ID:  ${self:custom.otherfile.lineTokishirazuLlcBachan.${self:provider.stage}.ADMIN_GROUP_ID}
      ORDER_GROUP_ID:  ${self:custom.otherfile.lineTokishirazuLlcBachan.${self:provider.stage}.ORDER_GROUP_ID}

    events:
      - http:
          path: line-tokishirazu-llc-bachan
          method: post
          cors: true
  
  
  lineMinarai:
    handler: bin/line
    runtime: go1.x
    environment:
      CHARA_NAME:  ${self:custom.otherfile.lineTokishirazuLlcMinarai.${self:provider.stage}.CHARA_NAME}
      CHANNEL_SECRET: ${self:custom.otherfile.lineTokishirazuLlcMinarai.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.lineTokishirazuLlcMinarai.${self:provider.stage}.CHANNEL_TOKEN}
      ADMIN_GROUP_ID:  ${self:custom.otherfile.lineTokishirazuLlcMinarai.${self:provider.stage}.ADMIN_GROUP_ID}
      ORDER_GROUP_ID:  ${self:custom.otherfile.lineTokishirazuLlcMinarai.${self:provider.stage}.ORDER_GROUP_ID}

    events:
      - http:
          path: line-tokishirazu-llc-minarai
          method: post
          cors: true
  
  
  
