service: motenas
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./conf/dev.yml)}
  rust:
    dockerTag: 'some-custom-tag'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  linebot:
    handler: bin/linebot
    runtime: go1.x
    environment:
      CHANNEL_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.CHANNEL_SECRET}
      CHANNEL_TOKEN: ${self:custom.otherfile.environment.${self:provider.stage}.CHANNEL_TOKEN}

    events:
      - http:
          path: linebot
          method: post
          cors: true
  
